name: Code Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript-typescript', 'python']
  
